package com.example.scale1.ui.scale
object Defines {
    const val CURRENT_WEEK = "Semana corrente"
    const val FIND_DATE = "Filtrar data"
    const val TEXT_ALL_FILTER = "Todos"
    const val TEXT_OK = "OK"
    const val TEXT_CANCEL = "Cancelar"
    const val SCALE_WEEK = "Escala Semanal :"
    const val DATE_FORMAT = "dd/MM/yyyy"
    const val MONDAY = "Segunda-Feira"
    const val TUESDAY = "Terça-Feira"
    const val WEDNESDAY = "Quarta-Feira"
    const val THURSDAY = "Quinta-Feira"
    const val FRIDAY = "Sexta-Feira"
    const val LOADING = "Carregando..."
    const val FILTER_PEOPLE = "Filtrar pessoas"
    const val FILTERED_PEOPLE = "Filtro pessoas :"
    const val NEXT = ">>"
    const val PREVIOUS = "<<"
}